# Generated by Django 5.2 on 2026-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_parent_post_shared_post_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quoted_post_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
