# Generated by Django 5.2 on 2026-05-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('mention', 'Mencion'), ('reply', 'Respuesta'), ('repost', 'Reposteado')], max_length=50),
        ),
    ]
