# Generated by Django 5.2 on 2026-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('follow_request', 'Solicitud de seguimiento'), ('mention', 'Mencion'), ('reply', 'Respuesta'), ('repost', 'Reposteado')], max_length=50),
        ),
    ]
